version: '3'

services:
  ec-cube:
    build:
      context: .
      args:
        - TAG=8.1-apache
    environment:
      - APP_DEBUG=0
      - WEB_DRIVER_HOST=browser
      - WEB_DRIVER_PORT=4444
      - BASE_URL=https://ec-cube
      - MAILCATCHER_HOST=mailcatcher
      - ECCUBE_RESTRICT_FILE_UPLOAD=${ECCUBE_RESTRICT_FILE_UPLOAD:-0}
      - TRUSTED_HOSTS=.*
    volumes:
      - ./app:/var/www/html/app
      - ./codeception:/var/www/html/codeception
      - ./html:/var/www/html/html
      - ./src:/var/www/html/src
      - ./var/log:/var/www/html/var/log
      - downloads:/var/www/html/codeception/_support/_downloads
      - repos:/var/www/html/repos

  package-api:
    image: eccube/mock-package-api:composer2
    environment:
      - MOCK_REPO_DIR=/repos
    volumes:
      - repos:/repos
  browser:
    build:
      dockerfile_inline: |
        FROM selenium/standalone-chrome
        USER root
    environment:
      - TZ=Asia/Tokyo
      - SCREEN_WIDTH=1680
      - SCREEN_HEIGHT=1020
      - VNC_NO_PASSWORD=1
    volumes:
      - downloads:/home/seluser/Downloads
    ports:
      - "5900:5900"
      - "7900:7900"
    networks:
      - backend

volumes:
  downloads:
  repos: