name: E2E test for EC-CUBE
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    paths:
      - '**'
      - '!*.md'
jobs:
  codeception:
    name: Codeception
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4 ]
        db: [ pgsql ]
        group: [ 'admin01', 'admin02', 'admin03', 'front', 'restrict-fileupload', 'installer' ]
        include:
          - db: pgsql
            database_url: postgres://postgres:password@127.0.0.1:5432/eccube_db
            database_server_version: 14
          - group: 'admin01'
            app_env: 'codeception'
          - group: 'admin02'
            app_env: 'codeception'
          - group: 'admin03'
            app_env: 'codeception'
          - group: 'front'
            app_env: 'codeception'
          - group: 'restrict-fileupload'
            app_env: 'codeception'
          - group: 'installer'
            app_env: 'install'

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup to EC-CUBE
        env:
          APP_ENV: ${{ matrix.app_env }}
        run: |
          docker compose -f docker-compose.yml -f docker-compose.pgsql.yml -f docker-compose.e2e.yml up -d --build --wait
          docker compose exec --user=www-data ec-cube bash -c 'echo "APP_ENV=${APP_ENV}" > .env'
          docker compose exec --user=www-data ec-cube bash -c 'for d in $(ls codeception/_data/plugins | grep 1.0.0); do (cd codeception/_data/plugins/$d; tar zcf ../../../../repos/${d}.tgz *); done'

      - name: Setup restrict file upload
        if: ${{ matrix.group == 'restrict-fileupload' }}
        run: docker compose exec --user=www-data  ec-cube bash -c 'echo "ECCUBE_RESTRICT_FILE_UPLOAD=1" >> .env'

      - name: Codeception
        if: ${{ matrix.group != 'restrict-fileupload' }}
        run: docker compose exec --user=www-data  ec-cube vendor/bin/codecept -vvv run acceptance --env chrome,docker -g "${{ matrix.group }}" --skip-group restrict-file-upload --html report.html

      - name: Codeception with Restrict file upload
        if: ${{ matrix.group == 'restrict-fileupload' }}
        run: docker compose exec --user=www-data  ec-cube vendor/bin/codecept -vvv run acceptance --env chrome,docker -g "${{ matrix.group }}" --html report.html

      - name: Upload evidence
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-evidence
          path: codeception/_output/
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-logs
          path: var/log/
