name: E2E test for EC-CUBE
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    paths:
      - '**'
      - '!*.md'
jobs:
  codeception:
    name: Codeception
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        group: [ 'admin01', 'admin02', 'admin03', 'front', 'restrict-fileupload', 'installer' ]
        include:
          - group: 'admin01'
            app_env: 'codeception'
          - group: 'admin02'
            app_env: 'codeception'
          - group: 'admin03'
            app_env: 'codeception'
          - group: 'front'
            app_env: 'codeception'
          - group: 'restrict-fileupload'
            app_env: 'codeception'
          - group: 'installer'
            app_env: 'install'

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run codeception
        run: |
          .github/workflows/e2e-test.sh -e "${{ matrix.app_env }}" -g "${{ matrix.group }}"

      - name: Upload evidence
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-evidence
          path: codeception/_output/

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-logs
          path: var/log/
